---
name: build-hyprland
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '25 21 * * 1'  # 2:25pm MT Mondays
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-hyprland.yml'
      - '.github/workflows/build.yml'
      - 'build/hyprland/*'
      - 'build/base/*'
      - '!**/README.md'
  workflow_dispatch:

jobs:
  build_hyprland:
    name: Build and push image
    permissions:
      contents: read
      packages: write
      id-token: write
    secrets: inherit
    strategy:
      max-parallel: 4
      matrix:
        upstream_suffix:
          - ""
          - "nvidia"
    uses: ./.github/workflows/build.yml
    with:
      permutation: "hyprland"
      image_suffix: ${{ matrix.upstream_suffix }}

